const weather = [
    {
        name:'晴',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d00.gif'
    },
    {
        name:'多云',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d01.gif'
    },
    {
        name:'阴',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d02.gif'
    },
    {
        name:'阵雨',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d03.gif'
    },
    {
        name:'雷阵雨',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d04.gif'
    },
    {
        name:'雨夹雪',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d06.gif'
    },
    {
        name:'小雨',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d07.gif'
    },
    {
        name:'中雨',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d08.gif'
    },
    {
        name:'大雨',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d09.gif'
    },
    {
        name:'暴雨',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d10.gif'
    },
    {
        name:'大暴雨',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d11.gif'
    },
    {
        name:'特大暴雨',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d12.gif'
    },
    {
        name:'阵雪',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d13.gif'
    },
    {
        name:'小雪',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d14.gif'
    },
    {
        name:'中雪',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d15.gif'
    },
    {
        name:'大雪',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d16.gif'
    },
    {
        name:'暴雪',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d17.gif'
    },
    {
        name:'雾',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d18.gif'
    },
    {
        name:'霾',
        url:'http://www.weather.com.cn/m/i/icon_weather/42x30/d53.gif'
    },
]
export default weather

